# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/fiddler-everywhere"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock]
exclude_navigation: ["knowledge-base/*"]
## List your directory names and order here, like this:
navigation:
    knowledge-base:
        position: 10
    getting-started:
        title: Getting Started
        position: 1
    user-guide:
        title: User Guide
        position: 2
    user-guide/settings:
        title: Settings
        position: 0
    user-guide/settings/general:
        title: General
        position: 0
    user-guide/settings/https:
        title: HTTPS
        position: 1
    user-guide/settings/connections:
        title: Connections
        position: 2
    user-guide/settings/gateway:
        title: Gateway
        position: 3
    user-guide/toolbar:
        title: Toolbar
        position: 1

## Product title
product: "Progress Telerik Fiddler"
platform: fiddler-everywhere 

## The application virtual path
baseurl: /fiddler-everywhere

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "fiddler"
        editable: true

has_kb_portal: true
has_api_reference: false

# Feedback Form Google Sheet ID
ff-sheet-id: 84c25215-7f22-0eb3-160f-78751ef7a337

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:lprcix5e19g'
gcs_api_key: 'AIzaSyCR292MCaU5T4cBKtvla6ZJTpPjQuM6dtU'

edit_repo_url: https://github.com/telerik/fiddler-everywhere-docs/edit/master
download: https://www.telerik.com/download/fiddler-everywhere
nav:
  "What's New": https://www.telerik.com/support/whats-new/fiddler-everywhere
  "Release History": https://www.telerik.com/support/whats-new/fiddler-everywhere/release-history
  "About": https://www.telerik.com/fiddler-everywhere

footer:
-
  title: "Getting Started"
  links:
    "Download Now": https://www.telerik.com/download/fiddler-everywhere
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/fiddler
    "Blogs": https://www.telerik.com/blogs/tag/fiddler
    "Feedback Portal": https://feedback.telerik.com/fiddler-everywhere
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/TelerikFiddler/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
